# Generated by Django 4.2.2 on 2023-06-08 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('serial', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('falla', models.CharField(max_length=200)),
                ('accesorios', models.CharField(max_length=300)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDeReparacion',
            fields=[
                ('numero_orden', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('reparacion_realizada', models.CharField(max_length=200)),
                ('valor', models.IntegerField()),
                ('tiempo_garantia', models.PositiveIntegerField(default=0)),
                ('reparada', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mack.cliente')),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mack.consola')),
            ],
        ),
    ]
